version: "3.8"
services:
  app:
    restart: always
    build: .
    ports:
      - 5000:5000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
